name = "improv-passthrough"
main = "src/index.ts"
compatibility_date = "2023-02-16"

[env.staging]
vars = { ENVIRONMENT = "staging", SECRET = "123", MATRIX_HOOKSHOT_HOST = "https://i0.tf/hookshot/webhook" }

[env.production]
vars = { ENVIRONMENT = "production" }
